---
# tasks file for ita_role_adapter_deploy

- name: create action plugins folder
  become: yes
  file:
    path: "/usr/share/ansible/plugins/action/"
    state: directory
    mode: '0755'

- name: copy action_plugin interface script
  become: yes
  copy:
    src: "{{ role_path }}/files/action_plugins/ita_role_adapter_gather.py"
    dest: "/usr/share/ansible/plugins/action/ita_role_adapter_gather.py"

- name: copy action_plugin interface script
  become: yes
  copy:
    src: "{{ role_path }}/files/action_plugins/ita_role_adapter_deploy.py"
    dest: "/usr/share/ansible/plugins/action/ita_role_adapter_deploy.py"
